from __future__ import annotations

import traceback
import uuid
from pathlib import Path

import typer

from .git_ops import (
    check_tools,
    commit,
    create_branch,
    create_pr,
    delete_branch,
    detect_install_command,
    detect_test_command,
    ensure_stack_ready,
    has_changes,
    is_dirty,
    push,
    run_agent,
    run_shell_command,
    sync_repo,
)
from .manifest import load_manifest
from .ticket import Ticket, parse_ticket


def run_ticket(
    ticket_path: Path,
    repo_key: str,
    manifest_path: Path | None = None,
) -> str:
    check_tools()

    manifest = load_manifest(manifest_path)
    if repo_key not in manifest.repos:
        available = ", ".join(manifest.repos.keys())
        raise ValueError(f"Repo '{repo_key}' not found in manifest. Available: {available}")
    repo = manifest.repos[repo_key]

    ticket = parse_ticket(ticket_path)
    if ticket.target_repo != repo_key:
        typer.echo(
            f"Warning: ticket target_repo='{ticket.target_repo}' does not match "
            f"--repo='{repo_key}'. Using --repo.",
            err=True,
        )

    if repo.local_path.exists() and is_dirty(repo.local_path):
        raise RuntimeError(
            f"Working tree at {repo.local_path} is dirty. "
            "Commit or stash your changes before running."
        )
    sync_repo(repo.local_path, repo.github, repo.default_branch)

    short_uuid = uuid.uuid4().hex[:8]
    branch = f"factory/{ticket.id.lower()}-{short_uuid}"
    create_branch(repo.local_path, branch)

    try:
        exit_code = run_agent(repo.local_path, _build_prompt(ticket))
        if exit_code != 0:
            raise RuntimeError(f"Claude Code exited with code {exit_code}.")

        if not has_changes(repo.local_path):
            delete_branch(repo.local_path, branch, repo.default_branch)
            raise RuntimeError("Agent produced no changes. Branch deleted.")

        install_cmd = repo.build_command or detect_install_command(repo.local_path)
        if install_cmd:
            result = run_shell_command(install_cmd, repo.local_path)
            if result.returncode != 0:
                typer.echo(
                    f"\nInstall/build failed. Branch '{branch}' preserved for inspection.",
                    err=True,
                )
                raise RuntimeError(f"Install/build failed (exit {result.returncode}).")

        test_cmd = repo.test_command or detect_test_command(repo.local_path)
        if test_cmd:
            if test_cmd.startswith("make "):
                ensure_stack_ready(repo.local_path)
            result = run_shell_command(test_cmd, repo.local_path)
            if result.returncode != 0:
                typer.echo(
                    f"\nTests failed. Branch '{branch}' preserved for inspection.",
                    err=True,
                )
                raise RuntimeError(f"Tests failed (exit {result.returncode}).")

        commit_msg = f"{ticket.id}: {ticket.title}"
        commit(repo.local_path, commit_msg)
        push(repo.local_path, branch)

        pr_url = create_pr(
            repo.local_path,
            title=commit_msg,
            body=_build_pr_body(ticket),
            base=repo.default_branch,
            head=branch,
        )

        typer.echo(f"\nPR opened: {pr_url}")
        return pr_url

    except RuntimeError:
        raise
    except Exception:
        typer.echo(
            f"\nUnexpected error on branch '{branch}':\n{traceback.format_exc()}",
            err=True,
        )
        raise


def _build_prompt(ticket: Ticket) -> str:
    parts = [
        "You are working on a task described by the following ticket.",
        "",
        f"Ticket ID: {ticket.id}",
        f"Title: {ticket.title}",
        "",
        "## Acceptance Criteria",
        "",
        ticket.acceptance_criteria,
    ]
    if ticket.notes:
        parts += ["", "## Notes", "", ticket.notes]
    if ticket.scope_paths:
        parts += ["", "## Scope", "", "Only modify files matching these patterns:"]
        parts += [f"  - {p}" for p in ticket.scope_paths]
    parts += [
        "",
        "---",
        "",
        "Make the necessary changes to satisfy the acceptance criteria.",
        "Do NOT run git commit. Do NOT run git push. Only edit files.",
        "When you are done, stop.",
    ]
    return "\n".join(parts)


def _build_pr_body(ticket: Ticket) -> str:
    return (
        f"## Acceptance Criteria\n\n"
        f"{ticket.acceptance_criteria}\n\n"
        f"---\n\n"
        f"_Generated by ai\\_factory_"
    )
